version: 2

models:

# dim_customer
  - name: dim_customer
    description: "Dimension table for customer data."
    columns:
      - name: customer_key
        description: "The unique identifier for each customer."
        tests:
          - not_null   # Ensures that every customer_id is populated
          - unique     # Ensures that customer_id is unique
          
      - name: account_number
        description: "The account number associated with the customer."
      
      - name: email_address
        description: "The customer's email address."
      
      - name: email_promotion
        description: "A numeric value indicating the level of email promotion engagement."
      
      - name: email_promotion_segment
        description: "Segment categorizing customers based on email promotion engagement."
      
      - name: first_name
        description: "The first name of the customer."
      
      - name: last_name
        description: "The last name of the customer."
      
      - name: middle_name
        description: "The middle name of the customer."
      
      - name: person_type
        description: "Indicates the type of person (individual, store, etc.)."
      
      - name: sales_location
        description: "The geographical sales location associated with the customer."
      
      - name: us_customer
        description: "Indicates whether the customer is from the US or Non-US."
        tests:
          - accepted_values:
              values: ['US', 'Non-US']  # Ensures that the values are only 'US' or 'Non-US'
              quote: true               # This ensures that the values are treated as strings

# dim_date
  - name: dim_date
    description: "Dimension table for date-related data."
    columns:
      - name: date_key
        description: "The unique identifier for each date (in YYYYMMDD format)."
        tests:
          - not_null   # Ensures date_key is populated
          - unique     # Ensures each date_key is unique

      - name: day_of_month
        description: "The day of the month."

      - name: day_of_week
        description: "The day of the week."

      - name: day_of_week_iso
        description: "ISO standard day of the week."

      - name: day_of_week_name
        description: "The name of the day of the week (e.g., Monday)."

      - name: day_of_week_name_short
        description: "Short name of the day of the week (e.g., Mon)."

      - name: day_of_year
        description: "The day number in the year."

      - name: iso_week_end_date
        description: "The end date of the ISO week."

      - name: iso_week_of_year
        description: "The ISO week number in the year."

      - name: iso_week_start_date
        description: "The start date of the ISO week."

      - name: month_end_date
        description: "The end date of the month."

      - name: month_name
        description: "The full name of the month (e.g., January)."

      - name: month_name_short
        description: "The abbreviated name of the month (e.g., Jan)."

      - name: month_of_year
        description: "The month number in the year."

      - name: month_start_date
        description: "The start date of the month."

      - name: next_date_day
        description: "The next day’s date."

      - name: prior_date_day
        description: "The previous day’s date."

      - name: prior_year_date_day
        description: "The same day in the prior year."

      - name: prior_year_iso_week_end_date
        description: "The end date of the ISO week in the prior year."

      - name: prior_year_iso_week_of_year
        description: "The ISO week number in the prior year."

      - name: prior_year_iso_week_start_date
        description: "The start date of the ISO week in the prior year."

      - name: prior_year_month_end_date
        description: "The end date of the month in the prior year."

      - name: prior_year_month_start_date
        description: "The start date of the month in the prior year."

      - name: prior_year_over_year_date_day
        description: "Year-over-year comparison date in the prior year."

      - name: prior_year_week_end_date
        description: "The end date of the week in the prior year."

      - name: prior_year_week_of_year
        description: "The week number in the prior year."

      - name: prior_year_week_start_date
        description: "The start date of the week in the prior year."

      - name: quarter_end_date
        description: "The end date of the quarter."

      - name: quarter_of_year
        description: "The quarter number in the year."

      - name: quarter_start_date
        description: "The start date of the quarter."

      - name: week_end_date
        description: "The end date of the week."

      - name: week_of_year
        description: "The week number in the year."

      - name: week_start_date
        description: "The start date of the week."

      - name: year_end_date
        description: "The end date of the year."

      - name: year_number
        description: "The year number."

      - name: year_start_date
        description: "The start date of the year."


# dim_salesperson
  - name: dim_salesperson
    description: "Dimension table for salesperson data."
    columns:
      - name: salesperson_key
        description: "The unique identifier for each salesperson."
        tests:
          - not_null   # Ensures that every salesperson_id is populated
          - unique     # Ensures that salesperson_id is unique

      - name: birth_date
        description: "The birth date of the salesperson."
      
      - name: current_sales_quota
        description: "The current sales quota for the salesperson."


      - name: gender
        description: "The gender of the salesperson."


      - name: hire_date
        description: "The date the salesperson was hired."
      
      - name: job_title
        description: "The job title of the salesperson."
      
      - name: latest_quota_date
        description: "The date of the latest sales quota assigned."
      
      - name: latest_sales_quota
        description: "The latest sales quota for the salesperson."


      - name: marital_status
        description: "The marital status of the salesperson."

      - name: organization_level
        description: "The organization level of the salesperson."


      - name: sales_last_year
        description: "The total sales made by the salesperson last year."


      - name: sales_ytd
        description: "The year-to-date sales for the salesperson."


      - name: sick_leave_hours
        description: "The number of sick leave hours for the salesperson."


      - name: territory_key
        description: "The identifier for the territory the salesperson is responsible for."


      - name: vacation_hours
        description: "The number of vacation hours for the salesperson."

# dim_salesterritory
  - name: dim_salesterritory
    description: "Dimension table for sales territory data."
    columns:
      - name: territory_key
        description: "The unique identifier for each sales territory."
        tests:
          - not_null   # Ensures that territory_id is populated
          - unique     # Ensures that territory_id is unique

      - name: country_region_code
        description: "The country or region code for the sales territory."
      
      - name: group_name
        description: "The group name of the sales territory."
      
      - name: name
        description: "The name of the sales territory."

      - name: sales_last_year
        description: "The total sales for the territory in the last year."

      - name: sales_ranking_last_year
        description: "The sales ranking for the territory in the last year."

      - name: sales_ranking_ytd
        description: "The sales ranking for the territory year-to-date."


      - name: sales_ytd
        description: "The year-to-date sales for the territory."


      - name: state_count
        description: "The number of states or provinces associated with the sales territory."


      - name: territory_id
        description: "The identifier for the territory."


#dim_product
  - name: dim_product
    description: "Dimension table for products, includes details about product, subcategory, and category."
    columns:
      - name: product_key
        description: "Unique identifier for each product."
        tests:
          - unique
          - not_null

      - name: product_name
        description: "Name of the product."


      - name: product_number
        description: "Unique product number for tracking."


      - name: product_model
        description: "Model name of the product."


      - name: product_subcategory_key
        description: "Foreign key to DimProductSubcategory."


      - name: subcategory_name
        description: "Name of the product subcategory (denormalized from DimProductSubcategory)."

      - name: product_category_key
        description: "Foreign key to DimProductCategory."

      - name: category_name
        description: "Name of the product category (denormalized from DimProductCategory)."

      - name: product_age
        description: "Age of the product in years (calculated)."

      - name: is_discontinued
        description: "Flag indicating if the product is discontinued."

      - name: gross_margin
        description: "Gross margin for the product, calculated as (ListPrice - StandardCost) / ListPrice."

      - name: seasonal_flag
        description: "Indicates whether the product is seasonal (Summer, Winter, Non-Seasonal)."

#dim_productcategory
  - name: dim_product_category
    description: "Dimension table for product categories."
    columns:
      - name: product_category_key
        description: "Unique identifier for each product category."
        tests:
          - unique
          - not_null

      - name: category_name
        description: "Name of the product category."

      - name: product_count
        description: "Total number of products in this category (calculated)."

      - name: active_products
        description: "Count of active products (not discontinued) in this category (calculated)."

#dim_productsubcategory
  - name: dim_product_subcategory
    description: "Dimension table for product subcategories."
    columns:
      - name: product_subcategory_key
        description: "Unique identifier for each product subcategory."
        tests:
          - unique
          - not_null

      - name: subcategory_name
        description: "Name of the product subcategory."

      - name: product_category_key
        description: "Foreign key to DimProductCategory."
        tests:
          - not_null
          - relationships:
              to: ref('dim_product_category')
              field: product_category_key

      - name: product_category_name
        description: "Denormalized category name from DimProductCategory."

      - name: subcategory_product_count
        description: "Total number of products in this subcategory (calculated)."

# dim_salesdetail:
  - name: dim_saledetail  # Name of the dimension model
    description: "Dimension table for sales order line item details. Each row represents a product within a sales order."
    columns:
      - name: sales_detail_key
        description: "Unique identifier for the sales order line item."
        tests:
          - unique
          - not_null

      - name: sales_order_key
        description: "Foreign key linking to FactSalesOrderHeader."
        tests:
          - relationships:
              to: ref('fact_salesorderheader')
              field: sales_order_key

      - name: product_key
        description: "Foreign key linking to DimProduct, representing the product in the order."
        tests:
          - relationships:
              to: ref('dim_product')
              field: product_key

      - name: order_quantity
        description: "The quantity of the product ordered."

      - name: unit_price
        description: "The price per unit of the product."

      - name: unit_price_discount
        description: "The discount applied to the unit price."

      - name: sales_amount
        description: "The total sales amount for the product line, calculated as order_quantity * unit_price."

      - name: discount_amount
        description: "The total discount amount for the product line, calculated as order_quantity * unit_price_discount."

      - name: line_total
        description: "The total amount for the line, including any discounts and adjustments."

  # dim_currency
  - name: dim_currency
    description: "Dimension table for currency details. Each row represents a currency."

    columns:
      - name: currency_rate_id
        description: "Unique identifier for the currency rate."
        tests:
          - not_null

      - name: currency_rate_date
        description: "The date the currency rate is applicable."

      - name: from_currency_code
        description: "Currency code for the originating currency."

      - name: to_currency_code
        description: "Currency code for the destination currency."

      - name: from_currency_name
        description: "Name of the originating currency."

      - name: to_currency_name
        description: "Name of the destination currency."

      - name: average_rate
        description: "The average rate between the two currencies."

      - name: end_of_day_rate
        description: "The end-of-day rate between the two currencies."
