snowflake_datawarehouse:
  outputs:
    dev:
      account: <your_snowflake_account>
      database: AIRBYTE_DATABASE
      password: <user_password>
      role: ACCOUNTADMIN
      schema: SOURCE
      threads: 1
      type: snowflake
      user: BACHKHOA144
      warehouse: AIRBYTE_WAREHOUSE
  target: devß
