snowflake_datawarehouse:
  outputs:
    dev:
      account: gqa15546.east-us-2.azure
      database: AIRBYTE_DATABASE
      password: Sifoftheraven1!
      role: ACCOUNTADMIN
      schema: SOURCE
      threads: 1
      type: snowflake
      user: BACHKHOA144
      warehouse: AIRBYTE_WAREHOUSE
  target: dev
