snowflake_datawarehouse:
  outputs:
    dev:
      account: <snowflake_id>
      database: AIRBYTE_DATABASE
      password: <password>
      role: ACCOUNTADMIN
      schema: SOURCE
      threads: 1
      type: snowflake
      user: BACHKHOA144
      warehouse: AIRBYTE_WAREHOUSE
  target: dev
